### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by Kapilmishra29** [ShreyaDhananjay/EcommerceWebsite#1]
Hello, Thanks for your help for guiding people like me. here, my issue is that post installing all the required flask packages, I am not able to run the flask app.

Request you to add requirements.txt or steps to run this app. Many thanks!

**Comment by ShreyaDhananjay** [comment]
Hi, this repository is not being maintained so I will not be making any changes to the master branch. 

There is a requirements.txt file in the test1 branch, however, I have not tested installing with that to see if it works.
